FROM python:3.10-slim

WORKDIR /app

COPY requirements.ui.txt .
RUN pip install -r requirements.ui.txt

COPY chatbot_client ./chatbot_client

EXPOSE 7860

CMD ["streamlit", "run", "chatbot_client/chat_ui.py", "--server.address=0.0.0.0", "--server.port=7860"]
