FROM python:3.10-slim

WORKDIR /app

COPY requirements.ui.txt .
RUN pip install --no-cache-dir -r requirements.ui.txt

COPY chatbot_client ./chatbot_client

WORKDIR /app/chatbot_client

CMD ["streamlit", "run", "chat_ui.py", "--server.address=0.0.0.0"]
