FROM python:3.10-slim

WORKDIR /app

# Install UI dependencies
COPY requirements.ui.txt .
RUN pip install --no-cache-dir -r requirements.ui.txt

# Copy UI code
COPY chatbot_client ./chatbot_client

WORKDIR /app/chatbot_client

EXPOSE 8501

CMD ["streamlit", "run", "chat_ui.py", "--server.address=0.0.0.0"]
