FROM python:3.10-slim

WORKDIR /app

COPY requirements.backend.txt .
RUN pip install --no-cache-dir -r requirements.backend.txt

# Copy backend code
COPY rag_service ./rag_service

# Make startup script executable
RUN chmod +x rag_service/start.sh

WORKDIR /app

CMD ["./rag_service/start.sh"]
